### ISSUE TITLE
Fixed broken links PR#101

### ISSUE THREAD

**Issue by Saichethan** [systers/systers.github.io#102]
## Description
As a USER,
I need fix couple of broken links,
so that I can make website more interactive & responsive.

## Mocks
http://systers.io/RGSoC/2018.html
http://systers.io/Outreachy/2017.html

### Update [Required]

index.html
### Enhancement to Update [Optional]
- [ ] [LIST ITEMS]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
[INSERT NUMBER HERE] hours 
5-10 min

**Comment by Saichethan** [comment]
Two broken links in index.html are fixed 
1.Outreachy
2.RGSoC

**Comment by sara-02** [comment]
@Saichethan You have not added any information in the issue, you just copied the format. Please update the issue, else we will have to close it.

**Comment by sara-02** [comment]
It would be great if you can share screenshots of the broken linking, and add the estimates in the issue.

**Comment by Saichethan** [comment]
![screenshot 16](https://user-images.githubusercontent.com/34788026/36720471-32f70430-1bce-11e8-84d5-68716d23d9d3.png)
![screenshot 17](https://user-images.githubusercontent.com/34788026/36720478-38579138-1bce-11e8-8e90-d0d0a5e21bb1.png)

**Comment by AnkitKhatri55555** [comment]
@sara-02 ,I think similar issue is already there,#80

**Comment by sara-02** [comment]
@AnkitKhatri55555 no, the problem here is the name of the RGSOC and Outreachy folders have changed. @Saichethan Correct me if I am wrong.

**Comment by Saichethan** [comment]
@sara-02 , you are correct !

**Comment by divyanshu-rawat** [comment]
@Saichethan please update your issue information as well instead of copying the format 👍

**Comment by Saichethan** [comment]
@divyanshu-rawat  I think I changed comment if there is something I am missing

**Comment by divyanshu-rawat** [comment]
@Saichethan Thanks 👍 
But still, there are some changes needed to be done like
 - [INSERT NUMBER HERE] hours Remove this as well as you have already mentioned 5-10 Minutes.
 - (Enhancement to Update)Remove this as well as it is optional.

And the good practice is to attach screenshots of the issue in Mocks.
And it would be great if you can attach the link to the [index.html ](https://github.com/systers/systers.github.io/blob/master/index.html) in the update section as well in order to explain it better to the community members going through this issue.
I hope it helps @sara-02 correct me If I am wrong 👍

**Comment by Tharangi** [comment]
Closing as this issue is resolved now.
