### ISSUE TITLE
Size of social media icons should be reduced  in mobile view 

### ISSUE THREAD

**Issue by anumehaagrawal** [systers/systers.github.io#106]
## Description
As a user,
I need reduce the size of icons in mobile
so that I can improve UI

## Mocks
![screenshot-2018-2-28 systers open source projects by systers 1](https://user-images.githubusercontent.com/25412153/36776053-7d5c3a2e-1c8a-11e8-914f-736bb51cbdc7.png)

### Update 
- Footer code needs to be added to all the files . The code can be updated from the source code on systers.io
- styles.css needs to be updated

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
40 minutes

**Comment by shreyateeza** [comment]
@anumehaagrawal Please write the names of all these files which require this change in Update [Required] of Acceptance Criteria section. :wink:

**Comment by akshitac8** [comment]
Hello,
Is this bug up for solving?

**Comment by anumehaagrawal** [comment]
@akshitac8 Yes you can solve this . Make sure you test it in different browsers as well :)

**Comment by akshitac8** [comment]
Ohkay @anumehaagrawal, Thank you

**Comment by akshitac8** [comment]
Can I know the files, I need to edit.

**Comment by shreyateeza** [comment]
@akshitac These files you have to edit -
index.html
 newcomers.html
 member-levels.html
 open-source-workflow.html
 reporting-guidelines.html
 contactus.html
 code-of-conduct.html
 gsoc/2009.html
 gsoc/2010.html
 gsoc/2011.html
 gsoc/2012.html
 gsoc/2013.html
 gsoc/2014.html
 gsoc/2015.html
 gsoc/2016.html
 gsoc/2017.html
 gsoc/2009.html
 RGSoC/2018.html
 Outreachy/2017.html

**Comment by akshitac8** [comment]
Thank you for sharing the files.

**Comment by akshitac8** [comment]
Hey @shreyateeza The current look for [Systers Website](http://systers.io/) is

![image](https://user-images.githubusercontent.com/21353757/37242263-6c2cd60a-248c-11e8-8725-b2dce7acc199.png)

Instead of removing the spaces between images, 
![](https://user-images.githubusercontent.com/25412153/36776053-7d5c3a2e-1c8a-11e8-914f-736bb51cbdc7.png)

I think only decreasing the size gives a much better UI.

![image](https://user-images.githubusercontent.com/21353757/37242271-931d1388-248c-11e8-86b3-a9d4453f12f2.png)
What do you think?

**Comment by akshitac8** [comment]
Hello,
Can I get update over this issue.
Thank you:)

**Comment by akshitac8** [comment]
@anumehaagrawal @sara-02 Can I get an update on this so that I can move forward??

**Comment by anumehaagrawal** [comment]
@akshitac8  Yes you may proceed , the size of the icons need to be reduced :)

**Comment by akshitac8** [comment]
Thank you :)

**Comment by shreyateeza** [comment]
@akshitac8 What you suggested is better. So you can go ahead with it. :)

**Comment by akshitac8** [comment]
Hello, @shreyateeza @anumehaagrawal @sara-02 I have created the PR #164  in reference to this issue.
KIndly review the changes :)

**Comment by shreyateeza** [comment]
Hi @akshitac8! As per the [Systers Open Source workflow](http://systers.io/open-source-workflow), firstly this issue needs to be approved by a maintainer first. Secondly, you should ask a maintainer if you can solve this issue. Previously many such PRs were closed which did not follow the Systers Open Source Workflow. So according to me, you should be on a safer side else your PR might get closed. Also, this issue is not yet approved. 
@sara-02 what do you suggest in this case?

**Comment by akshitac8** [comment]
@shreyateeza I had asked to work on this issue a few days earlier and thought that it was assigned to me.

**Comment by BaaniLeen** [comment]
@akshitac8 The issue needs to be assigned by any of the project mentors, before working as per the Systers OSS workflow to basically avoid multiple people from working on the same issue. As suggested by @shreyateeza please follow the Systers OSS workflow hereon, http://systers.io/open-source-workflow. :)

**Comment by akshitac8** [comment]
Hey @BaaniLeen I thought it was assigned to me by a mentor as seen [in this comment](https://github.com/systers/systers.github.io/issues/106#issuecomment-371393885).
I shall follow the Systers OSS. Thanks for the link :slightly_smiling_face:

**Comment by divyanshu-rawat** [comment]
@akshitac8 actually @anumehaagrawal is not a Mentor as mentioned by @BaaniLeen and @shreyateeza that only a Mentor can assign this issue to you.
So, it's still not assigned to you.

**Comment by ancyp** [comment]
@divyanshu-rawat did you mean to assign it to @akshitac8  her or are we waiting on something?
Looks like she has a PR already.

**Comment by BaaniLeen** [comment]
Closing this issue since we have switched to font awesome icons, which are consistent for mobile view too.
