### ISSUE TITLE
web page should have 'TOP' button which will scroll to top of the page.

### ISSUE THREAD

**Issue by santosh62** [systers/systers.github.io#148]
## Description
As we don't have a fixed nav-bar ,the `top` button will help us to go to the top of the page
When a user scrolls past a certain point on the website, this helpful button appears, enabling users to easily return to the top of a page.It won't be visible until the user scrolls to that position, and if they scroll back up above that position, the button will disappear

we can place this button at right-bottom corner .

*here is the sample pen of `top` button.*

https://codepen.io/santosh62/full/MVwmvZ/

### Update [Required]
- [ ] index.html
- [ ] code-of-conduct.html
- [ ] contactus.html
- [ ] gsoc/2009.html
- [ ] gsoc/2010.html
- [ ] gsoc/20111.html
- [ ] gsoc/2012.html
- [ ] gsoc/2013.html
- [ ] gsoc/2014.html
- [ ] gsoc/2015.html
- [ ] gsoc/2016.html
- [ ] gsoc/2017.html
- [ ] member-levels.html
- [ ] newcomers.html
- [ ] open-source-workflow.html
- [ ] Outreachy/2017.html
- [ ] reporting-guidelines.html
- [ ]  RGSoC/2018.html

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hours

**Comment by santosh62** [comment]
@MeepyMay @Janiceilene @prachi1210 @divyanshu-rawat
should i work on this??

**Comment by divyanshu-rawat** [comment]
@rbhatia46 Have you asked anyone before taking up this issue and sending PR?

**Comment by rbhatia46** [comment]
@divyanshu-rawat I am sorry I wasn't aware of this. I just had a look at this issue and found this was a quick fix for the website, therefore, I had sent the PR.

**Comment by divyanshu-rawat** [comment]
@rbhatia46  So, you were not aware that when you contribute to open-source then before sending the PR you have to ask the maintainers to assign you the issue? Maybe it's your first time in open-source I guess Am I right 👍

**Comment by MeepyMay** [comment]
Please update to our template's standards. [Use this issue as a reference.](https://github.com/systers/celebration/issues/6)

Shorten the description, add the "Mocks" section back since you have an example, then move the action items from the description to the "Acceptance Criteria." For example, "Add Back to Top button in all web pages:" with the list that you wrote down above.

It needs to go under "Enhancement to Update" since the "Back to Top" button is nice to have but not necessary to navigate the website.
