### ISSUE TITLE
Wiki Sidebar Update

### ISSUE THREAD

**Issue by ExactlyMay** [systers/systers.github.io#170]
## Description
As a newcomer,
I need to navigate the repo successfully,
so that I can understand where the project is in its development.

## Mocks
![screen shot 2018-04-19 at 3 47 20 pm](https://user-images.githubusercontent.com/2440938/39014663-06dcb230-43e9-11e8-997c-96a89b7c55e8.png)

### Update [Required]
- [x] Update to [the template](https://docs.google.com/document/d/1h53P1h5g9hWEUsnOhpl9PgVzbWEGhTMIP2Pyta-MYSA/edit?usp=sharing) as discussed by the Community.
### Enhancement to Update [Optional]
- [x] Link all GSoC/Outreachy student's pages if applicable.
- [x] Link Final Reports page if applicable.

## Definition of Done
- [x] All of the required items are completed.
- [ ] Approval by 3 Community Members.

## Estimation
10-30 minutes

**Comment by BaaniLeen** [comment]
@MeepyMay Can I work on this issue?

**Comment by Tharangi** [comment]
@BaaniLeen You can work on this.

**Comment by divyanshu-rawat** [comment]
@BaaniLeen Issue Assigned to you 👍

**Comment by BaaniLeen** [comment]
@MeepyMay @divyanshu-rawat @Tharangi Please review the updates done in the [Wiki Sidebar](https://github.com/systers/systers.github.io/wiki) and let me know if I missed out on something! :)

**Comment by MeepyMay** [comment]
@BaaniLeen The sidebar is still missing. 
![screen shot 2018-04-25 at 10 54 02 am](https://user-images.githubusercontent.com/2440938/39253986-196269a8-4877-11e8-8f53-5ebc5863c81d.png)

**Comment by BaaniLeen** [comment]
@MeepyMay Sorry! I misunderstood it. Does it work now?

**Comment by isabelcosta** [comment]
@BaaniLeen @MeepyMay I think the sidebar looks better now :) I jsut have one suggestion. Because there is a sidebar the existing pages list gets collapsed. Since the wiki has different types of pages, I would suggest to link the already existing pages like this:
What do you think?

![image](https://user-images.githubusercontent.com/11148726/39261152-82b14168-48b3-11e8-9ea1-6b259cbab5c9.png)

**Comment by BaaniLeen** [comment]
@isabelcosta Surely! I can do that, but would not this happen every time a project updates the Wiki Sidebar? And if we add the same data in every project's Sidebar, would not that be very redundant. What are your views upon this?

**Comment by isabelcosta** [comment]
@BaaniLeen Yes it will! The the pages list contains all the pages. You can choose how you present the pages in the sidebar instead of just seeing it as an unordered list. You don't have to create new pages and making redundant, you'll just have to put the link like this: [GSoC 2018] ... (https://github.com/systers/systers.github.io/wiki/GSoC-2018). Because the page already exists.

All the pages will be listed on that list. But with the sidebar you get to choose which ones should be highlighted and be on the "menu", and how they should be treated as an hierarchy.

![image](https://user-images.githubusercontent.com/11148726/39262661-e8ba075c-48b7-11e8-886c-d11051ae3dd9.png)

Does this make sense?

**Comment by isabelcosta** [comment]
@BaaniLeen you can see an example here https://github.com/Netflix/ndbench/wiki/Configuration. You'll see that that page is in the pages list, but is highlighted in the sidebar, which is visible when someone goes to the wiki. This is from a study previouly done about wiki sidebars available in the Systers Open Source Drive.

**Comment by divyanshu-rawat** [comment]
@isabelcosta I do with you on the same but I am a little bit confused what's the meaning of highlighted in the sidebar citing your example of an attached link does is it mean that Plugin list item contains unordered list items that are pointing to other plugins.

**Comment by divyanshu-rawat** [comment]
@BaaniLeen Project Requirements,Setup and Install are still pointing to systers gh repo. 😃

**Comment by BaaniLeen** [comment]
@isabelcosta @divyanshu-rawat Adding onto Isabelle's idea, I feel we can have a single customised sidebar with all the projects (and their related info under it as an unordered list ). And we can perhaps have each project have different pages to which the hyperlink on the project name relates to.

Something like :

Home
About Systers
Contribution Guidelines
Projects
     - Github Pages
            +Documentation
                -> Getting Started
                -> Coding Standards
            + GSoC students
                 -> 2018
      -Powerup 
            +Documentation
                -> Getting Started
                -> Coding Standards
            + GSoC students
                 -> 2018

**Comment by divyanshu-rawat** [comment]
@BaaniLeen I liked your idea of enhancing the @isabelcosta idea.
I also think we can have a single customized sidebar with all the projects (and their related info under it as an unordered list ) etc.
let's wait for other mentors opinion on the same. 👍

**Comment by BaaniLeen** [comment]
@divyanshu-rawat I have purposely added the links to the Github repo currently for the Setup & Install instructions & for the Project Requirements. Shall I add separate pages for the same in the Wiki itself? 

Also, can I update the README file of the Repo to have the Project Requirement, Getting Started & Setup and Install Instructions as follow? Shall I create a separate issue for the same?
![screen shot 2018-04-25 at 9 36 06 pm](https://user-images.githubusercontent.com/22029744/39266725-70785628-48e8-11e8-9236-acf5ebfdc664.png)
![screen shot 2018-04-25 at 9 36 18 pm](https://user-images.githubusercontent.com/22029744/39266811-b28e4252-48e8-11e8-99b3-71e498305b99.png)

**Comment by isabelcosta** [comment]
@divyanshu-rawat sorry for the confusion. When I say highlight, its just the idea of giving more focus to a page than the other. By comparison, the sidebar shows the same pages but gives an idea of the Parent Pages, and the pages that are subpages, instead of having all list without any type of hierarchy.
In this image, the sidebar gives a better idea of the content of the wiki by having the bullets representing the pages through a hierarchy.

![image](https://user-images.githubusercontent.com/11148726/39266729-bd33b172-48c2-11e8-859d-9e8ece799957.png)

About the links linking to the repo, I noticed that too, but I understand that there isn't a discussion yet about the proper content of the Wiki pages.

@BaaniLeen In my opinion I think you can create a page for getting started with the content you're showing and another for the "Setup & Install", with the "Set up for Developers" content.

But yes we can wait for maintainers and mentors opinions :)

**Comment by BaaniLeen** [comment]
@MeepyMay Shall I add separate pages in the wiki itself for the Setup & Install instructions & for the Project Requirements of Gh-Pages? What's your view about it. :)

**Comment by ancyp** [comment]
@ExactlyMay

**Comment by isabelcosta** [comment]
Updated the wiki again, to have a link for the other pages of the wiki (almost all are linkable from wiki):
https://github.com/systers/systers.github.io/wiki

![image](https://user-images.githubusercontent.com/11148726/70748601-3ac05c00-1d22-11ea-9bc0-b7731a01cca6.png)
