### ISSUE TITLE
Travis.yml suggestion

### ISSUE THREAD

**Issue by Saichethan** [systers/systers.github.io#78]
## Description
Adding "bundler_args: --retry 5" in travis.yml to retry build for five times
As a [USER],
I need [TO DO THIS],
so that I can [ACCOMPLISH THAT].

## Mocks
[INSERT RELEVANT PNG FILE]

### Update [Required]
- [x] [LIST ITEMS]
### Enhancement to Update [Optional]
- [x] [LIST ITEMS]

## Definition of Done
- [x] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
[INSERT NUMBER HERE] hours 
1-5 min

**Comment by Saichethan** [comment]
I have seen tarvis docs generally it generally runs 3 tests specifically 5 doesn't have any significance it's just we can increase number of iterations which can help

**Comment by shreyateeza** [comment]
@Saichethan Update your issue according to the issue template.
Also its `Travis` and not `Tarvis`. :wink:

**Comment by Saichethan** [comment]
I type on phone "auto correct" .......😐

**Comment by shreyateeza** [comment]
You can still correct it by clicking the edit button near the issue name. :wink:

**Comment by sara-02** [comment]
@Saichethan the reason I am saying that is because if it an issue on our code or our configuration of travis then retrying 5 times will still not help. But yes in some senarios it is an infra issue and then we would love to have an auto-retry, although it should not be immediate but at an interval of say 5 mins. If it still does not work, then a 3rd try at an interval of 10 mins. What do you say about this approach?
I think more than 3 tries will be a overkill

**Comment by MeepyMay** [comment]
Does not follow template structure. Closing Issue.
